/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedRegionsIndexRouteImport } from './routes/_authenticated/regions/index'
import { Route as AuthenticatedPurchasingIndexRouteImport } from './routes/_authenticated/purchasing/index'
import { Route as AuthenticatedProvincesIndexRouteImport } from './routes/_authenticated/provinces/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedVipTierIndexRouteImport } from './routes/_authenticated/vip/tier/index'
import { Route as AuthenticatedVipPrivateRuleIndexRouteImport } from './routes/_authenticated/vip/private-rule/index'
import { Route as AuthenticatedVipPointRuleIndexRouteImport } from './routes/_authenticated/vip/point-rule/index'
import { Route as AuthenticatedVipCustomerIndexRouteImport } from './routes/_authenticated/vip/customer/index'
import { Route as AuthenticatedSalarySalesTargetsIndexRouteImport } from './routes/_authenticated/salary/sales-targets/index'
import { Route as AuthenticatedSalarySalesActualsIndexRouteImport } from './routes/_authenticated/salary/sales-actuals/index'
import { Route as AuthenticatedPurchasingSuppliersIndexRouteImport } from './routes/_authenticated/purchasing/suppliers/index'
import { Route as AuthenticatedPurchasingShipmentsIndexRouteImport } from './routes/_authenticated/purchasing/shipments/index'
import { Route as AuthenticatedPurchasingPortsIndexRouteImport } from './routes/_authenticated/purchasing/ports/index'
import { Route as AuthenticatedPurchasingContractsIndexRouteImport } from './routes/_authenticated/purchasing/contracts/index'
import { Route as AuthenticatedVipCustomerIdRouteImport } from './routes/_authenticated/vip/customer/$id'
import { Route as AuthenticatedPurchasingContractsIdIndexRouteImport } from './routes/_authenticated/purchasing/contracts/$id/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegionsIndexRoute =
  AuthenticatedRegionsIndexRouteImport.update({
    id: '/regions/',
    path: '/regions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingIndexRoute =
  AuthenticatedPurchasingIndexRouteImport.update({
    id: '/purchasing/',
    path: '/purchasing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvincesIndexRoute =
  AuthenticatedProvincesIndexRouteImport.update({
    id: '/provinces/',
    path: '/provinces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipTierIndexRoute =
  AuthenticatedVipTierIndexRouteImport.update({
    id: '/vip/tier/',
    path: '/vip/tier/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipPrivateRuleIndexRoute =
  AuthenticatedVipPrivateRuleIndexRouteImport.update({
    id: '/vip/private-rule/',
    path: '/vip/private-rule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipPointRuleIndexRoute =
  AuthenticatedVipPointRuleIndexRouteImport.update({
    id: '/vip/point-rule/',
    path: '/vip/point-rule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipCustomerIndexRoute =
  AuthenticatedVipCustomerIndexRouteImport.update({
    id: '/vip/customer/',
    path: '/vip/customer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalarySalesTargetsIndexRoute =
  AuthenticatedSalarySalesTargetsIndexRouteImport.update({
    id: '/salary/sales-targets/',
    path: '/salary/sales-targets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalarySalesActualsIndexRoute =
  AuthenticatedSalarySalesActualsIndexRouteImport.update({
    id: '/salary/sales-actuals/',
    path: '/salary/sales-actuals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingSuppliersIndexRoute =
  AuthenticatedPurchasingSuppliersIndexRouteImport.update({
    id: '/purchasing/suppliers/',
    path: '/purchasing/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingShipmentsIndexRoute =
  AuthenticatedPurchasingShipmentsIndexRouteImport.update({
    id: '/purchasing/shipments/',
    path: '/purchasing/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingPortsIndexRoute =
  AuthenticatedPurchasingPortsIndexRouteImport.update({
    id: '/purchasing/ports/',
    path: '/purchasing/ports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingContractsIndexRoute =
  AuthenticatedPurchasingContractsIndexRouteImport.update({
    id: '/purchasing/contracts/',
    path: '/purchasing/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipCustomerIdRoute =
  AuthenticatedVipCustomerIdRouteImport.update({
    id: '/vip/customer/$id',
    path: '/vip/customer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingContractsIdIndexRoute =
  AuthenticatedPurchasingContractsIdIndexRouteImport.update({
    id: '/purchasing/contracts/$id/',
    path: '/purchasing/contracts/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/provinces/': typeof AuthenticatedProvincesIndexRoute
  '/purchasing/': typeof AuthenticatedPurchasingIndexRoute
  '/regions/': typeof AuthenticatedRegionsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
  '/vip/customer/$id': typeof AuthenticatedVipCustomerIdRoute
  '/purchasing/contracts/': typeof AuthenticatedPurchasingContractsIndexRoute
  '/purchasing/ports/': typeof AuthenticatedPurchasingPortsIndexRoute
  '/purchasing/shipments/': typeof AuthenticatedPurchasingShipmentsIndexRoute
  '/purchasing/suppliers/': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/salary/sales-actuals/': typeof AuthenticatedSalarySalesActualsIndexRoute
  '/salary/sales-targets/': typeof AuthenticatedSalarySalesTargetsIndexRoute
  '/vip/customer/': typeof AuthenticatedVipCustomerIndexRoute
  '/vip/point-rule/': typeof AuthenticatedVipPointRuleIndexRoute
  '/vip/private-rule/': typeof AuthenticatedVipPrivateRuleIndexRoute
  '/vip/tier/': typeof AuthenticatedVipTierIndexRoute
  '/purchasing/contracts/$id/': typeof AuthenticatedPurchasingContractsIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/provinces': typeof AuthenticatedProvincesIndexRoute
  '/purchasing': typeof AuthenticatedPurchasingIndexRoute
  '/regions': typeof AuthenticatedRegionsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
  '/vip/customer/$id': typeof AuthenticatedVipCustomerIdRoute
  '/purchasing/contracts': typeof AuthenticatedPurchasingContractsIndexRoute
  '/purchasing/ports': typeof AuthenticatedPurchasingPortsIndexRoute
  '/purchasing/shipments': typeof AuthenticatedPurchasingShipmentsIndexRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/salary/sales-actuals': typeof AuthenticatedSalarySalesActualsIndexRoute
  '/salary/sales-targets': typeof AuthenticatedSalarySalesTargetsIndexRoute
  '/vip/customer': typeof AuthenticatedVipCustomerIndexRoute
  '/vip/point-rule': typeof AuthenticatedVipPointRuleIndexRoute
  '/vip/private-rule': typeof AuthenticatedVipPrivateRuleIndexRoute
  '/vip/tier': typeof AuthenticatedVipTierIndexRoute
  '/purchasing/contracts/$id': typeof AuthenticatedPurchasingContractsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/provinces/': typeof AuthenticatedProvincesIndexRoute
  '/_authenticated/purchasing/': typeof AuthenticatedPurchasingIndexRoute
  '/_authenticated/regions/': typeof AuthenticatedRegionsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
  '/_authenticated/vip/customer/$id': typeof AuthenticatedVipCustomerIdRoute
  '/_authenticated/purchasing/contracts/': typeof AuthenticatedPurchasingContractsIndexRoute
  '/_authenticated/purchasing/ports/': typeof AuthenticatedPurchasingPortsIndexRoute
  '/_authenticated/purchasing/shipments/': typeof AuthenticatedPurchasingShipmentsIndexRoute
  '/_authenticated/purchasing/suppliers/': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/_authenticated/salary/sales-actuals/': typeof AuthenticatedSalarySalesActualsIndexRoute
  '/_authenticated/salary/sales-targets/': typeof AuthenticatedSalarySalesTargetsIndexRoute
  '/_authenticated/vip/customer/': typeof AuthenticatedVipCustomerIndexRoute
  '/_authenticated/vip/point-rule/': typeof AuthenticatedVipPointRuleIndexRoute
  '/_authenticated/vip/private-rule/': typeof AuthenticatedVipPrivateRuleIndexRoute
  '/_authenticated/vip/tier/': typeof AuthenticatedVipTierIndexRoute
  '/_authenticated/purchasing/contracts/$id/': typeof AuthenticatedPurchasingContractsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/customers/'
    | '/employees/'
    | '/products/'
    | '/provinces/'
    | '/purchasing/'
    | '/regions/'
    | '/transactions/'
    | '/user/'
    | '/vip/customer/$id'
    | '/purchasing/contracts/'
    | '/purchasing/ports/'
    | '/purchasing/shipments/'
    | '/purchasing/suppliers/'
    | '/salary/sales-actuals/'
    | '/salary/sales-targets/'
    | '/vip/customer/'
    | '/vip/point-rule/'
    | '/vip/private-rule/'
    | '/vip/tier/'
    | '/purchasing/contracts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/customers'
    | '/employees'
    | '/products'
    | '/provinces'
    | '/purchasing'
    | '/regions'
    | '/transactions'
    | '/user'
    | '/vip/customer/$id'
    | '/purchasing/contracts'
    | '/purchasing/ports'
    | '/purchasing/shipments'
    | '/purchasing/suppliers'
    | '/salary/sales-actuals'
    | '/salary/sales-targets'
    | '/vip/customer'
    | '/vip/point-rule'
    | '/vip/private-rule'
    | '/vip/tier'
    | '/purchasing/contracts/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/customers/'
    | '/_authenticated/employees/'
    | '/_authenticated/products/'
    | '/_authenticated/provinces/'
    | '/_authenticated/purchasing/'
    | '/_authenticated/regions/'
    | '/_authenticated/transactions/'
    | '/_authenticated/user/'
    | '/_authenticated/vip/customer/$id'
    | '/_authenticated/purchasing/contracts/'
    | '/_authenticated/purchasing/ports/'
    | '/_authenticated/purchasing/shipments/'
    | '/_authenticated/purchasing/suppliers/'
    | '/_authenticated/salary/sales-actuals/'
    | '/_authenticated/salary/sales-targets/'
    | '/_authenticated/vip/customer/'
    | '/_authenticated/vip/point-rule/'
    | '/_authenticated/vip/private-rule/'
    | '/_authenticated/vip/tier/'
    | '/_authenticated/purchasing/contracts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regions/': {
      id: '/_authenticated/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof AuthenticatedRegionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/': {
      id: '/_authenticated/purchasing/'
      path: '/purchasing'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof AuthenticatedPurchasingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provinces/': {
      id: '/_authenticated/provinces/'
      path: '/provinces'
      fullPath: '/provinces/'
      preLoaderRoute: typeof AuthenticatedProvincesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/tier/': {
      id: '/_authenticated/vip/tier/'
      path: '/vip/tier'
      fullPath: '/vip/tier/'
      preLoaderRoute: typeof AuthenticatedVipTierIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/private-rule/': {
      id: '/_authenticated/vip/private-rule/'
      path: '/vip/private-rule'
      fullPath: '/vip/private-rule/'
      preLoaderRoute: typeof AuthenticatedVipPrivateRuleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/point-rule/': {
      id: '/_authenticated/vip/point-rule/'
      path: '/vip/point-rule'
      fullPath: '/vip/point-rule/'
      preLoaderRoute: typeof AuthenticatedVipPointRuleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/customer/': {
      id: '/_authenticated/vip/customer/'
      path: '/vip/customer'
      fullPath: '/vip/customer/'
      preLoaderRoute: typeof AuthenticatedVipCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/sales-targets/': {
      id: '/_authenticated/salary/sales-targets/'
      path: '/salary/sales-targets'
      fullPath: '/salary/sales-targets/'
      preLoaderRoute: typeof AuthenticatedSalarySalesTargetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/sales-actuals/': {
      id: '/_authenticated/salary/sales-actuals/'
      path: '/salary/sales-actuals'
      fullPath: '/salary/sales-actuals/'
      preLoaderRoute: typeof AuthenticatedSalarySalesActualsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/suppliers/': {
      id: '/_authenticated/purchasing/suppliers/'
      path: '/purchasing/suppliers'
      fullPath: '/purchasing/suppliers/'
      preLoaderRoute: typeof AuthenticatedPurchasingSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/shipments/': {
      id: '/_authenticated/purchasing/shipments/'
      path: '/purchasing/shipments'
      fullPath: '/purchasing/shipments/'
      preLoaderRoute: typeof AuthenticatedPurchasingShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/ports/': {
      id: '/_authenticated/purchasing/ports/'
      path: '/purchasing/ports'
      fullPath: '/purchasing/ports/'
      preLoaderRoute: typeof AuthenticatedPurchasingPortsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/contracts/': {
      id: '/_authenticated/purchasing/contracts/'
      path: '/purchasing/contracts'
      fullPath: '/purchasing/contracts/'
      preLoaderRoute: typeof AuthenticatedPurchasingContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/customer/$id': {
      id: '/_authenticated/vip/customer/$id'
      path: '/vip/customer/$id'
      fullPath: '/vip/customer/$id'
      preLoaderRoute: typeof AuthenticatedVipCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/contracts/$id/': {
      id: '/_authenticated/purchasing/contracts/$id/'
      path: '/purchasing/contracts/$id'
      fullPath: '/purchasing/contracts/$id/'
      preLoaderRoute: typeof AuthenticatedPurchasingContractsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProvincesIndexRoute: typeof AuthenticatedProvincesIndexRoute
  AuthenticatedPurchasingIndexRoute: typeof AuthenticatedPurchasingIndexRoute
  AuthenticatedRegionsIndexRoute: typeof AuthenticatedRegionsIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
  AuthenticatedVipCustomerIdRoute: typeof AuthenticatedVipCustomerIdRoute
  AuthenticatedPurchasingContractsIndexRoute: typeof AuthenticatedPurchasingContractsIndexRoute
  AuthenticatedPurchasingPortsIndexRoute: typeof AuthenticatedPurchasingPortsIndexRoute
  AuthenticatedPurchasingShipmentsIndexRoute: typeof AuthenticatedPurchasingShipmentsIndexRoute
  AuthenticatedPurchasingSuppliersIndexRoute: typeof AuthenticatedPurchasingSuppliersIndexRoute
  AuthenticatedSalarySalesActualsIndexRoute: typeof AuthenticatedSalarySalesActualsIndexRoute
  AuthenticatedSalarySalesTargetsIndexRoute: typeof AuthenticatedSalarySalesTargetsIndexRoute
  AuthenticatedVipCustomerIndexRoute: typeof AuthenticatedVipCustomerIndexRoute
  AuthenticatedVipPointRuleIndexRoute: typeof AuthenticatedVipPointRuleIndexRoute
  AuthenticatedVipPrivateRuleIndexRoute: typeof AuthenticatedVipPrivateRuleIndexRoute
  AuthenticatedVipTierIndexRoute: typeof AuthenticatedVipTierIndexRoute
  AuthenticatedPurchasingContractsIdIndexRoute: typeof AuthenticatedPurchasingContractsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProvincesIndexRoute: AuthenticatedProvincesIndexRoute,
  AuthenticatedPurchasingIndexRoute: AuthenticatedPurchasingIndexRoute,
  AuthenticatedRegionsIndexRoute: AuthenticatedRegionsIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
  AuthenticatedVipCustomerIdRoute: AuthenticatedVipCustomerIdRoute,
  AuthenticatedPurchasingContractsIndexRoute:
    AuthenticatedPurchasingContractsIndexRoute,
  AuthenticatedPurchasingPortsIndexRoute:
    AuthenticatedPurchasingPortsIndexRoute,
  AuthenticatedPurchasingShipmentsIndexRoute:
    AuthenticatedPurchasingShipmentsIndexRoute,
  AuthenticatedPurchasingSuppliersIndexRoute:
    AuthenticatedPurchasingSuppliersIndexRoute,
  AuthenticatedSalarySalesActualsIndexRoute:
    AuthenticatedSalarySalesActualsIndexRoute,
  AuthenticatedSalarySalesTargetsIndexRoute:
    AuthenticatedSalarySalesTargetsIndexRoute,
  AuthenticatedVipCustomerIndexRoute: AuthenticatedVipCustomerIndexRoute,
  AuthenticatedVipPointRuleIndexRoute: AuthenticatedVipPointRuleIndexRoute,
  AuthenticatedVipPrivateRuleIndexRoute: AuthenticatedVipPrivateRuleIndexRoute,
  AuthenticatedVipTierIndexRoute: AuthenticatedVipTierIndexRoute,
  AuthenticatedPurchasingContractsIdIndexRoute:
    AuthenticatedPurchasingContractsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
