/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedWarehousesIndexRouteImport } from './routes/_authenticated/warehouses/index'
import { Route as AuthenticatedUserIndexRouteImport } from './routes/_authenticated/user/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedRegionsIndexRouteImport } from './routes/_authenticated/regions/index'
import { Route as AuthenticatedPurchasingIndexRouteImport } from './routes/_authenticated/purchasing/index'
import { Route as AuthenticatedProvincesIndexRouteImport } from './routes/_authenticated/provinces/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedProductGroupsIndexRouteImport } from './routes/_authenticated/product-groups/index'
import { Route as AuthenticatedPricingIndexRouteImport } from './routes/_authenticated/pricing/index'
import { Route as AuthenticatedPhysicalWarehousesIndexRouteImport } from './routes/_authenticated/physical-warehouses/index'
import { Route as AuthenticatedNationsIndexRouteImport } from './routes/_authenticated/nations/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCurrenciesIndexRouteImport } from './routes/_authenticated/currencies/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedVipTiersIndexRouteImport } from './routes/_authenticated/vip/tiers/index'
import { Route as AuthenticatedVipRecalcJobIndexRouteImport } from './routes/_authenticated/vip/recalc-job/index'
import { Route as AuthenticatedVipProductMappingIndexRouteImport } from './routes/_authenticated/vip/product-mapping/index'
import { Route as AuthenticatedVipPrivateRulesIndexRouteImport } from './routes/_authenticated/vip/private-rules/index'
import { Route as AuthenticatedVipPointRulesIndexRouteImport } from './routes/_authenticated/vip/point-rules/index'
import { Route as AuthenticatedVipCustomerIndexRouteImport } from './routes/_authenticated/vip/customer/index'
import { Route as AuthenticatedVipCustomerTargetIndexRouteImport } from './routes/_authenticated/vip/customer-target/index'
import { Route as AuthenticatedVipCustomerPlanIndexRouteImport } from './routes/_authenticated/vip/customer-plan/index'
import { Route as AuthenticatedToolsProductMergeIndexRouteImport } from './routes/_authenticated/tools/product-merge/index'
import { Route as AuthenticatedSalesReturnsIndexRouteImport } from './routes/_authenticated/sales/returns/index'
import { Route as AuthenticatedSalesReceiptsIndexRouteImport } from './routes/_authenticated/sales/receipts/index'
import { Route as AuthenticatedSalesOrdersIndexRouteImport } from './routes/_authenticated/sales/orders/index'
import { Route as AuthenticatedSalesInventorySummaryIndexRouteImport } from './routes/_authenticated/sales/inventory-summary/index'
import { Route as AuthenticatedSalesGoodsDescriptionsIndexRouteImport } from './routes/_authenticated/sales/goods-descriptions/index'
import { Route as AuthenticatedSalesExportsIndexRouteImport } from './routes/_authenticated/sales/exports/index'
import { Route as AuthenticatedSalesDeliveriesIndexRouteImport } from './routes/_authenticated/sales/deliveries/index'
import { Route as AuthenticatedSalesCashBankLedgerIndexRouteImport } from './routes/_authenticated/sales/cash-bank-ledger/index'
import { Route as AuthenticatedSalesArSummaryIndexRouteImport } from './routes/_authenticated/sales/ar-summary/index'
import { Route as AuthenticatedSalesArOpeningsIndexRouteImport } from './routes/_authenticated/sales/ar-openings/index'
import { Route as AuthenticatedSalesArLedgersIndexRouteImport } from './routes/_authenticated/sales/ar-ledgers/index'
import { Route as AuthenticatedSalesArAdjustmentsIndexRouteImport } from './routes/_authenticated/sales/ar-adjustments/index'
import { Route as AuthenticatedSalaryYearBonusIndexRouteImport } from './routes/_authenticated/salary/year-bonus/index'
import { Route as AuthenticatedSalarySetupIndexRouteImport } from './routes/_authenticated/salary/setup/index'
import { Route as AuthenticatedSalarySalesTargetsIndexRouteImport } from './routes/_authenticated/salary/sales-targets/index'
import { Route as AuthenticatedSalarySalesActualsIndexRouteImport } from './routes/_authenticated/salary/sales-actuals/index'
import { Route as AuthenticatedSalaryRulesIndexRouteImport } from './routes/_authenticated/salary/rules/index'
import { Route as AuthenticatedSalaryRegionPoolIndexRouteImport } from './routes/_authenticated/salary/region-pool/index'
import { Route as AuthenticatedSalaryPayrollRunIndexRouteImport } from './routes/_authenticated/salary/payroll-run/index'
import { Route as AuthenticatedSalaryPayrollResultIndexRouteImport } from './routes/_authenticated/salary/payroll-result/index'
import { Route as AuthenticatedSalaryPayrollConfigIndexRouteImport } from './routes/_authenticated/salary/payroll-config/index'
import { Route as AuthenticatedSalaryMonthlyIncomesIndexRouteImport } from './routes/_authenticated/salary/monthly-incomes/index'
import { Route as AuthenticatedSalaryImportIndexRouteImport } from './routes/_authenticated/salary/import/index'
import { Route as AuthenticatedSalaryAuditIndexRouteImport } from './routes/_authenticated/salary/audit/index'
import { Route as AuthenticatedSalaryAdjustmentsIndexRouteImport } from './routes/_authenticated/salary/adjustments/index'
import { Route as AuthenticatedPurchasingSuppliersIndexRouteImport } from './routes/_authenticated/purchasing/suppliers/index'
import { Route as AuthenticatedPurchasingShipmentsIndexRouteImport } from './routes/_authenticated/purchasing/shipments/index'
import { Route as AuthenticatedPurchasingPortsIndexRouteImport } from './routes/_authenticated/purchasing/ports/index'
import { Route as AuthenticatedPurchasingContractsIndexRouteImport } from './routes/_authenticated/purchasing/contracts/index'
import { Route as AuthenticatedPurchasingApSummaryIndexRouteImport } from './routes/_authenticated/purchasing/ap-summary/index'
import { Route as AuthenticatedProductionOrdersIndexRouteImport } from './routes/_authenticated/production/orders/index'
import { Route as AuthenticatedProductionBomsIndexRouteImport } from './routes/_authenticated/production/boms/index'
import { Route as AuthenticatedInventorySummaryIndexRouteImport } from './routes/_authenticated/inventory/summary/index'
import { Route as AuthenticatedInventoryOutboundsIndexRouteImport } from './routes/_authenticated/inventory/outbounds/index'
import { Route as AuthenticatedInventoryLotsIndexRouteImport } from './routes/_authenticated/inventory/lots/index'
import { Route as AuthenticatedInventoryLedgersIndexRouteImport } from './routes/_authenticated/inventory/ledgers/index'
import { Route as AuthenticatedInventoryInboundsIndexRouteImport } from './routes/_authenticated/inventory/inbounds/index'
import { Route as AuthenticatedAccessUsersIndexRouteImport } from './routes/_authenticated/access/users/index'
import { Route as AuthenticatedAccessUserRolesIndexRouteImport } from './routes/_authenticated/access/user-roles/index'
import { Route as AuthenticatedAccessRolesIndexRouteImport } from './routes/_authenticated/access/roles/index'
import { Route as AuthenticatedAccessPermissionsIndexRouteImport } from './routes/_authenticated/access/permissions/index'
import { Route as AuthenticatedVipCustomerIdRouteImport } from './routes/_authenticated/vip/customer/$id'
import { Route as AuthenticatedSalesOrdersIdIndexRouteImport } from './routes/_authenticated/sales/orders/$id/index'
import { Route as AuthenticatedSalesExportsIdIndexRouteImport } from './routes/_authenticated/sales/exports/$id/index'
import { Route as AuthenticatedSalesDeliveriesIdIndexRouteImport } from './routes/_authenticated/sales/deliveries/$id/index'
import { Route as AuthenticatedSalaryPayrollResultEmployeeIdIndexRouteImport } from './routes/_authenticated/salary/payroll-result/$employeeId/index'
import { Route as AuthenticatedPurchasingContractsIdIndexRouteImport } from './routes/_authenticated/purchasing/contracts/$id/index'
import { Route as AuthenticatedProductionOrdersIdIndexRouteImport } from './routes/_authenticated/production/orders/$id/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehousesIndexRoute =
  AuthenticatedWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserIndexRoute = AuthenticatedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRegionsIndexRoute =
  AuthenticatedRegionsIndexRouteImport.update({
    id: '/regions/',
    path: '/regions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingIndexRoute =
  AuthenticatedPurchasingIndexRouteImport.update({
    id: '/purchasing/',
    path: '/purchasing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvincesIndexRoute =
  AuthenticatedProvincesIndexRouteImport.update({
    id: '/provinces/',
    path: '/provinces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductGroupsIndexRoute =
  AuthenticatedProductGroupsIndexRouteImport.update({
    id: '/product-groups/',
    path: '/product-groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPricingIndexRoute =
  AuthenticatedPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPhysicalWarehousesIndexRoute =
  AuthenticatedPhysicalWarehousesIndexRouteImport.update({
    id: '/physical-warehouses/',
    path: '/physical-warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNationsIndexRoute =
  AuthenticatedNationsIndexRouteImport.update({
    id: '/nations/',
    path: '/nations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurrenciesIndexRoute =
  AuthenticatedCurrenciesIndexRouteImport.update({
    id: '/currencies/',
    path: '/currencies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipTiersIndexRoute =
  AuthenticatedVipTiersIndexRouteImport.update({
    id: '/vip/tiers/',
    path: '/vip/tiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipRecalcJobIndexRoute =
  AuthenticatedVipRecalcJobIndexRouteImport.update({
    id: '/vip/recalc-job/',
    path: '/vip/recalc-job/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipProductMappingIndexRoute =
  AuthenticatedVipProductMappingIndexRouteImport.update({
    id: '/vip/product-mapping/',
    path: '/vip/product-mapping/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipPrivateRulesIndexRoute =
  AuthenticatedVipPrivateRulesIndexRouteImport.update({
    id: '/vip/private-rules/',
    path: '/vip/private-rules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipPointRulesIndexRoute =
  AuthenticatedVipPointRulesIndexRouteImport.update({
    id: '/vip/point-rules/',
    path: '/vip/point-rules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipCustomerIndexRoute =
  AuthenticatedVipCustomerIndexRouteImport.update({
    id: '/vip/customer/',
    path: '/vip/customer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipCustomerTargetIndexRoute =
  AuthenticatedVipCustomerTargetIndexRouteImport.update({
    id: '/vip/customer-target/',
    path: '/vip/customer-target/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipCustomerPlanIndexRoute =
  AuthenticatedVipCustomerPlanIndexRouteImport.update({
    id: '/vip/customer-plan/',
    path: '/vip/customer-plan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsProductMergeIndexRoute =
  AuthenticatedToolsProductMergeIndexRouteImport.update({
    id: '/tools/product-merge/',
    path: '/tools/product-merge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesReturnsIndexRoute =
  AuthenticatedSalesReturnsIndexRouteImport.update({
    id: '/sales/returns/',
    path: '/sales/returns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesReceiptsIndexRoute =
  AuthenticatedSalesReceiptsIndexRouteImport.update({
    id: '/sales/receipts/',
    path: '/sales/receipts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIndexRoute =
  AuthenticatedSalesOrdersIndexRouteImport.update({
    id: '/sales/orders/',
    path: '/sales/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesInventorySummaryIndexRoute =
  AuthenticatedSalesInventorySummaryIndexRouteImport.update({
    id: '/sales/inventory-summary/',
    path: '/sales/inventory-summary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesGoodsDescriptionsIndexRoute =
  AuthenticatedSalesGoodsDescriptionsIndexRouteImport.update({
    id: '/sales/goods-descriptions/',
    path: '/sales/goods-descriptions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesExportsIndexRoute =
  AuthenticatedSalesExportsIndexRouteImport.update({
    id: '/sales/exports/',
    path: '/sales/exports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesDeliveriesIndexRoute =
  AuthenticatedSalesDeliveriesIndexRouteImport.update({
    id: '/sales/deliveries/',
    path: '/sales/deliveries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesCashBankLedgerIndexRoute =
  AuthenticatedSalesCashBankLedgerIndexRouteImport.update({
    id: '/sales/cash-bank-ledger/',
    path: '/sales/cash-bank-ledger/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesArSummaryIndexRoute =
  AuthenticatedSalesArSummaryIndexRouteImport.update({
    id: '/sales/ar-summary/',
    path: '/sales/ar-summary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesArOpeningsIndexRoute =
  AuthenticatedSalesArOpeningsIndexRouteImport.update({
    id: '/sales/ar-openings/',
    path: '/sales/ar-openings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesArLedgersIndexRoute =
  AuthenticatedSalesArLedgersIndexRouteImport.update({
    id: '/sales/ar-ledgers/',
    path: '/sales/ar-ledgers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesArAdjustmentsIndexRoute =
  AuthenticatedSalesArAdjustmentsIndexRouteImport.update({
    id: '/sales/ar-adjustments/',
    path: '/sales/ar-adjustments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryYearBonusIndexRoute =
  AuthenticatedSalaryYearBonusIndexRouteImport.update({
    id: '/salary/year-bonus/',
    path: '/salary/year-bonus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalarySetupIndexRoute =
  AuthenticatedSalarySetupIndexRouteImport.update({
    id: '/salary/setup/',
    path: '/salary/setup/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalarySalesTargetsIndexRoute =
  AuthenticatedSalarySalesTargetsIndexRouteImport.update({
    id: '/salary/sales-targets/',
    path: '/salary/sales-targets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalarySalesActualsIndexRoute =
  AuthenticatedSalarySalesActualsIndexRouteImport.update({
    id: '/salary/sales-actuals/',
    path: '/salary/sales-actuals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryRulesIndexRoute =
  AuthenticatedSalaryRulesIndexRouteImport.update({
    id: '/salary/rules/',
    path: '/salary/rules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryRegionPoolIndexRoute =
  AuthenticatedSalaryRegionPoolIndexRouteImport.update({
    id: '/salary/region-pool/',
    path: '/salary/region-pool/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryPayrollRunIndexRoute =
  AuthenticatedSalaryPayrollRunIndexRouteImport.update({
    id: '/salary/payroll-run/',
    path: '/salary/payroll-run/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryPayrollResultIndexRoute =
  AuthenticatedSalaryPayrollResultIndexRouteImport.update({
    id: '/salary/payroll-result/',
    path: '/salary/payroll-result/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryPayrollConfigIndexRoute =
  AuthenticatedSalaryPayrollConfigIndexRouteImport.update({
    id: '/salary/payroll-config/',
    path: '/salary/payroll-config/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryMonthlyIncomesIndexRoute =
  AuthenticatedSalaryMonthlyIncomesIndexRouteImport.update({
    id: '/salary/monthly-incomes/',
    path: '/salary/monthly-incomes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryImportIndexRoute =
  AuthenticatedSalaryImportIndexRouteImport.update({
    id: '/salary/import/',
    path: '/salary/import/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryAuditIndexRoute =
  AuthenticatedSalaryAuditIndexRouteImport.update({
    id: '/salary/audit/',
    path: '/salary/audit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryAdjustmentsIndexRoute =
  AuthenticatedSalaryAdjustmentsIndexRouteImport.update({
    id: '/salary/adjustments/',
    path: '/salary/adjustments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingSuppliersIndexRoute =
  AuthenticatedPurchasingSuppliersIndexRouteImport.update({
    id: '/purchasing/suppliers/',
    path: '/purchasing/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingShipmentsIndexRoute =
  AuthenticatedPurchasingShipmentsIndexRouteImport.update({
    id: '/purchasing/shipments/',
    path: '/purchasing/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingPortsIndexRoute =
  AuthenticatedPurchasingPortsIndexRouteImport.update({
    id: '/purchasing/ports/',
    path: '/purchasing/ports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingContractsIndexRoute =
  AuthenticatedPurchasingContractsIndexRouteImport.update({
    id: '/purchasing/contracts/',
    path: '/purchasing/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingApSummaryIndexRoute =
  AuthenticatedPurchasingApSummaryIndexRouteImport.update({
    id: '/purchasing/ap-summary/',
    path: '/purchasing/ap-summary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionOrdersIndexRoute =
  AuthenticatedProductionOrdersIndexRouteImport.update({
    id: '/production/orders/',
    path: '/production/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionBomsIndexRoute =
  AuthenticatedProductionBomsIndexRouteImport.update({
    id: '/production/boms/',
    path: '/production/boms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventorySummaryIndexRoute =
  AuthenticatedInventorySummaryIndexRouteImport.update({
    id: '/inventory/summary/',
    path: '/inventory/summary/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryOutboundsIndexRoute =
  AuthenticatedInventoryOutboundsIndexRouteImport.update({
    id: '/inventory/outbounds/',
    path: '/inventory/outbounds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryLotsIndexRoute =
  AuthenticatedInventoryLotsIndexRouteImport.update({
    id: '/inventory/lots/',
    path: '/inventory/lots/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryLedgersIndexRoute =
  AuthenticatedInventoryLedgersIndexRouteImport.update({
    id: '/inventory/ledgers/',
    path: '/inventory/ledgers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryInboundsIndexRoute =
  AuthenticatedInventoryInboundsIndexRouteImport.update({
    id: '/inventory/inbounds/',
    path: '/inventory/inbounds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessUsersIndexRoute =
  AuthenticatedAccessUsersIndexRouteImport.update({
    id: '/access/users/',
    path: '/access/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessUserRolesIndexRoute =
  AuthenticatedAccessUserRolesIndexRouteImport.update({
    id: '/access/user-roles/',
    path: '/access/user-roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessRolesIndexRoute =
  AuthenticatedAccessRolesIndexRouteImport.update({
    id: '/access/roles/',
    path: '/access/roles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessPermissionsIndexRoute =
  AuthenticatedAccessPermissionsIndexRouteImport.update({
    id: '/access/permissions/',
    path: '/access/permissions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVipCustomerIdRoute =
  AuthenticatedVipCustomerIdRouteImport.update({
    id: '/vip/customer/$id',
    path: '/vip/customer/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesOrdersIdIndexRoute =
  AuthenticatedSalesOrdersIdIndexRouteImport.update({
    id: '/sales/orders/$id/',
    path: '/sales/orders/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesExportsIdIndexRoute =
  AuthenticatedSalesExportsIdIndexRouteImport.update({
    id: '/sales/exports/$id/',
    path: '/sales/exports/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesDeliveriesIdIndexRoute =
  AuthenticatedSalesDeliveriesIdIndexRouteImport.update({
    id: '/sales/deliveries/$id/',
    path: '/sales/deliveries/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute =
  AuthenticatedSalaryPayrollResultEmployeeIdIndexRouteImport.update({
    id: '/salary/payroll-result/$employeeId/',
    path: '/salary/payroll-result/$employeeId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasingContractsIdIndexRoute =
  AuthenticatedPurchasingContractsIdIndexRouteImport.update({
    id: '/purchasing/contracts/$id/',
    path: '/purchasing/contracts/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductionOrdersIdIndexRoute =
  AuthenticatedProductionOrdersIdIndexRouteImport.update({
    id: '/production/orders/$id/',
    path: '/production/orders/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/currencies/': typeof AuthenticatedCurrenciesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/nations/': typeof AuthenticatedNationsIndexRoute
  '/physical-warehouses/': typeof AuthenticatedPhysicalWarehousesIndexRoute
  '/pricing/': typeof AuthenticatedPricingIndexRoute
  '/product-groups/': typeof AuthenticatedProductGroupsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/provinces/': typeof AuthenticatedProvincesIndexRoute
  '/purchasing/': typeof AuthenticatedPurchasingIndexRoute
  '/regions/': typeof AuthenticatedRegionsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/user/': typeof AuthenticatedUserIndexRoute
  '/warehouses/': typeof AuthenticatedWarehousesIndexRoute
  '/vip/customer/$id': typeof AuthenticatedVipCustomerIdRoute
  '/access/permissions/': typeof AuthenticatedAccessPermissionsIndexRoute
  '/access/roles/': typeof AuthenticatedAccessRolesIndexRoute
  '/access/user-roles/': typeof AuthenticatedAccessUserRolesIndexRoute
  '/access/users/': typeof AuthenticatedAccessUsersIndexRoute
  '/inventory/inbounds/': typeof AuthenticatedInventoryInboundsIndexRoute
  '/inventory/ledgers/': typeof AuthenticatedInventoryLedgersIndexRoute
  '/inventory/lots/': typeof AuthenticatedInventoryLotsIndexRoute
  '/inventory/outbounds/': typeof AuthenticatedInventoryOutboundsIndexRoute
  '/inventory/summary/': typeof AuthenticatedInventorySummaryIndexRoute
  '/production/boms/': typeof AuthenticatedProductionBomsIndexRoute
  '/production/orders/': typeof AuthenticatedProductionOrdersIndexRoute
  '/purchasing/ap-summary/': typeof AuthenticatedPurchasingApSummaryIndexRoute
  '/purchasing/contracts/': typeof AuthenticatedPurchasingContractsIndexRoute
  '/purchasing/ports/': typeof AuthenticatedPurchasingPortsIndexRoute
  '/purchasing/shipments/': typeof AuthenticatedPurchasingShipmentsIndexRoute
  '/purchasing/suppliers/': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/salary/adjustments/': typeof AuthenticatedSalaryAdjustmentsIndexRoute
  '/salary/audit/': typeof AuthenticatedSalaryAuditIndexRoute
  '/salary/import/': typeof AuthenticatedSalaryImportIndexRoute
  '/salary/monthly-incomes/': typeof AuthenticatedSalaryMonthlyIncomesIndexRoute
  '/salary/payroll-config/': typeof AuthenticatedSalaryPayrollConfigIndexRoute
  '/salary/payroll-result/': typeof AuthenticatedSalaryPayrollResultIndexRoute
  '/salary/payroll-run/': typeof AuthenticatedSalaryPayrollRunIndexRoute
  '/salary/region-pool/': typeof AuthenticatedSalaryRegionPoolIndexRoute
  '/salary/rules/': typeof AuthenticatedSalaryRulesIndexRoute
  '/salary/sales-actuals/': typeof AuthenticatedSalarySalesActualsIndexRoute
  '/salary/sales-targets/': typeof AuthenticatedSalarySalesTargetsIndexRoute
  '/salary/setup/': typeof AuthenticatedSalarySetupIndexRoute
  '/salary/year-bonus/': typeof AuthenticatedSalaryYearBonusIndexRoute
  '/sales/ar-adjustments/': typeof AuthenticatedSalesArAdjustmentsIndexRoute
  '/sales/ar-ledgers/': typeof AuthenticatedSalesArLedgersIndexRoute
  '/sales/ar-openings/': typeof AuthenticatedSalesArOpeningsIndexRoute
  '/sales/ar-summary/': typeof AuthenticatedSalesArSummaryIndexRoute
  '/sales/cash-bank-ledger/': typeof AuthenticatedSalesCashBankLedgerIndexRoute
  '/sales/deliveries/': typeof AuthenticatedSalesDeliveriesIndexRoute
  '/sales/exports/': typeof AuthenticatedSalesExportsIndexRoute
  '/sales/goods-descriptions/': typeof AuthenticatedSalesGoodsDescriptionsIndexRoute
  '/sales/inventory-summary/': typeof AuthenticatedSalesInventorySummaryIndexRoute
  '/sales/orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/sales/receipts/': typeof AuthenticatedSalesReceiptsIndexRoute
  '/sales/returns/': typeof AuthenticatedSalesReturnsIndexRoute
  '/tools/product-merge/': typeof AuthenticatedToolsProductMergeIndexRoute
  '/vip/customer-plan/': typeof AuthenticatedVipCustomerPlanIndexRoute
  '/vip/customer-target/': typeof AuthenticatedVipCustomerTargetIndexRoute
  '/vip/customer/': typeof AuthenticatedVipCustomerIndexRoute
  '/vip/point-rules/': typeof AuthenticatedVipPointRulesIndexRoute
  '/vip/private-rules/': typeof AuthenticatedVipPrivateRulesIndexRoute
  '/vip/product-mapping/': typeof AuthenticatedVipProductMappingIndexRoute
  '/vip/recalc-job/': typeof AuthenticatedVipRecalcJobIndexRoute
  '/vip/tiers/': typeof AuthenticatedVipTiersIndexRoute
  '/production/orders/$id/': typeof AuthenticatedProductionOrdersIdIndexRoute
  '/purchasing/contracts/$id/': typeof AuthenticatedPurchasingContractsIdIndexRoute
  '/salary/payroll-result/$employeeId/': typeof AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute
  '/sales/deliveries/$id/': typeof AuthenticatedSalesDeliveriesIdIndexRoute
  '/sales/exports/$id/': typeof AuthenticatedSalesExportsIdIndexRoute
  '/sales/orders/$id/': typeof AuthenticatedSalesOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/currencies': typeof AuthenticatedCurrenciesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/nations': typeof AuthenticatedNationsIndexRoute
  '/physical-warehouses': typeof AuthenticatedPhysicalWarehousesIndexRoute
  '/pricing': typeof AuthenticatedPricingIndexRoute
  '/product-groups': typeof AuthenticatedProductGroupsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/provinces': typeof AuthenticatedProvincesIndexRoute
  '/purchasing': typeof AuthenticatedPurchasingIndexRoute
  '/regions': typeof AuthenticatedRegionsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/user': typeof AuthenticatedUserIndexRoute
  '/warehouses': typeof AuthenticatedWarehousesIndexRoute
  '/vip/customer/$id': typeof AuthenticatedVipCustomerIdRoute
  '/access/permissions': typeof AuthenticatedAccessPermissionsIndexRoute
  '/access/roles': typeof AuthenticatedAccessRolesIndexRoute
  '/access/user-roles': typeof AuthenticatedAccessUserRolesIndexRoute
  '/access/users': typeof AuthenticatedAccessUsersIndexRoute
  '/inventory/inbounds': typeof AuthenticatedInventoryInboundsIndexRoute
  '/inventory/ledgers': typeof AuthenticatedInventoryLedgersIndexRoute
  '/inventory/lots': typeof AuthenticatedInventoryLotsIndexRoute
  '/inventory/outbounds': typeof AuthenticatedInventoryOutboundsIndexRoute
  '/inventory/summary': typeof AuthenticatedInventorySummaryIndexRoute
  '/production/boms': typeof AuthenticatedProductionBomsIndexRoute
  '/production/orders': typeof AuthenticatedProductionOrdersIndexRoute
  '/purchasing/ap-summary': typeof AuthenticatedPurchasingApSummaryIndexRoute
  '/purchasing/contracts': typeof AuthenticatedPurchasingContractsIndexRoute
  '/purchasing/ports': typeof AuthenticatedPurchasingPortsIndexRoute
  '/purchasing/shipments': typeof AuthenticatedPurchasingShipmentsIndexRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/salary/adjustments': typeof AuthenticatedSalaryAdjustmentsIndexRoute
  '/salary/audit': typeof AuthenticatedSalaryAuditIndexRoute
  '/salary/import': typeof AuthenticatedSalaryImportIndexRoute
  '/salary/monthly-incomes': typeof AuthenticatedSalaryMonthlyIncomesIndexRoute
  '/salary/payroll-config': typeof AuthenticatedSalaryPayrollConfigIndexRoute
  '/salary/payroll-result': typeof AuthenticatedSalaryPayrollResultIndexRoute
  '/salary/payroll-run': typeof AuthenticatedSalaryPayrollRunIndexRoute
  '/salary/region-pool': typeof AuthenticatedSalaryRegionPoolIndexRoute
  '/salary/rules': typeof AuthenticatedSalaryRulesIndexRoute
  '/salary/sales-actuals': typeof AuthenticatedSalarySalesActualsIndexRoute
  '/salary/sales-targets': typeof AuthenticatedSalarySalesTargetsIndexRoute
  '/salary/setup': typeof AuthenticatedSalarySetupIndexRoute
  '/salary/year-bonus': typeof AuthenticatedSalaryYearBonusIndexRoute
  '/sales/ar-adjustments': typeof AuthenticatedSalesArAdjustmentsIndexRoute
  '/sales/ar-ledgers': typeof AuthenticatedSalesArLedgersIndexRoute
  '/sales/ar-openings': typeof AuthenticatedSalesArOpeningsIndexRoute
  '/sales/ar-summary': typeof AuthenticatedSalesArSummaryIndexRoute
  '/sales/cash-bank-ledger': typeof AuthenticatedSalesCashBankLedgerIndexRoute
  '/sales/deliveries': typeof AuthenticatedSalesDeliveriesIndexRoute
  '/sales/exports': typeof AuthenticatedSalesExportsIndexRoute
  '/sales/goods-descriptions': typeof AuthenticatedSalesGoodsDescriptionsIndexRoute
  '/sales/inventory-summary': typeof AuthenticatedSalesInventorySummaryIndexRoute
  '/sales/orders': typeof AuthenticatedSalesOrdersIndexRoute
  '/sales/receipts': typeof AuthenticatedSalesReceiptsIndexRoute
  '/sales/returns': typeof AuthenticatedSalesReturnsIndexRoute
  '/tools/product-merge': typeof AuthenticatedToolsProductMergeIndexRoute
  '/vip/customer-plan': typeof AuthenticatedVipCustomerPlanIndexRoute
  '/vip/customer-target': typeof AuthenticatedVipCustomerTargetIndexRoute
  '/vip/customer': typeof AuthenticatedVipCustomerIndexRoute
  '/vip/point-rules': typeof AuthenticatedVipPointRulesIndexRoute
  '/vip/private-rules': typeof AuthenticatedVipPrivateRulesIndexRoute
  '/vip/product-mapping': typeof AuthenticatedVipProductMappingIndexRoute
  '/vip/recalc-job': typeof AuthenticatedVipRecalcJobIndexRoute
  '/vip/tiers': typeof AuthenticatedVipTiersIndexRoute
  '/production/orders/$id': typeof AuthenticatedProductionOrdersIdIndexRoute
  '/purchasing/contracts/$id': typeof AuthenticatedPurchasingContractsIdIndexRoute
  '/salary/payroll-result/$employeeId': typeof AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute
  '/sales/deliveries/$id': typeof AuthenticatedSalesDeliveriesIdIndexRoute
  '/sales/exports/$id': typeof AuthenticatedSalesExportsIdIndexRoute
  '/sales/orders/$id': typeof AuthenticatedSalesOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/currencies/': typeof AuthenticatedCurrenciesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/nations/': typeof AuthenticatedNationsIndexRoute
  '/_authenticated/physical-warehouses/': typeof AuthenticatedPhysicalWarehousesIndexRoute
  '/_authenticated/pricing/': typeof AuthenticatedPricingIndexRoute
  '/_authenticated/product-groups/': typeof AuthenticatedProductGroupsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/provinces/': typeof AuthenticatedProvincesIndexRoute
  '/_authenticated/purchasing/': typeof AuthenticatedPurchasingIndexRoute
  '/_authenticated/regions/': typeof AuthenticatedRegionsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/user/': typeof AuthenticatedUserIndexRoute
  '/_authenticated/warehouses/': typeof AuthenticatedWarehousesIndexRoute
  '/_authenticated/vip/customer/$id': typeof AuthenticatedVipCustomerIdRoute
  '/_authenticated/access/permissions/': typeof AuthenticatedAccessPermissionsIndexRoute
  '/_authenticated/access/roles/': typeof AuthenticatedAccessRolesIndexRoute
  '/_authenticated/access/user-roles/': typeof AuthenticatedAccessUserRolesIndexRoute
  '/_authenticated/access/users/': typeof AuthenticatedAccessUsersIndexRoute
  '/_authenticated/inventory/inbounds/': typeof AuthenticatedInventoryInboundsIndexRoute
  '/_authenticated/inventory/ledgers/': typeof AuthenticatedInventoryLedgersIndexRoute
  '/_authenticated/inventory/lots/': typeof AuthenticatedInventoryLotsIndexRoute
  '/_authenticated/inventory/outbounds/': typeof AuthenticatedInventoryOutboundsIndexRoute
  '/_authenticated/inventory/summary/': typeof AuthenticatedInventorySummaryIndexRoute
  '/_authenticated/production/boms/': typeof AuthenticatedProductionBomsIndexRoute
  '/_authenticated/production/orders/': typeof AuthenticatedProductionOrdersIndexRoute
  '/_authenticated/purchasing/ap-summary/': typeof AuthenticatedPurchasingApSummaryIndexRoute
  '/_authenticated/purchasing/contracts/': typeof AuthenticatedPurchasingContractsIndexRoute
  '/_authenticated/purchasing/ports/': typeof AuthenticatedPurchasingPortsIndexRoute
  '/_authenticated/purchasing/shipments/': typeof AuthenticatedPurchasingShipmentsIndexRoute
  '/_authenticated/purchasing/suppliers/': typeof AuthenticatedPurchasingSuppliersIndexRoute
  '/_authenticated/salary/adjustments/': typeof AuthenticatedSalaryAdjustmentsIndexRoute
  '/_authenticated/salary/audit/': typeof AuthenticatedSalaryAuditIndexRoute
  '/_authenticated/salary/import/': typeof AuthenticatedSalaryImportIndexRoute
  '/_authenticated/salary/monthly-incomes/': typeof AuthenticatedSalaryMonthlyIncomesIndexRoute
  '/_authenticated/salary/payroll-config/': typeof AuthenticatedSalaryPayrollConfigIndexRoute
  '/_authenticated/salary/payroll-result/': typeof AuthenticatedSalaryPayrollResultIndexRoute
  '/_authenticated/salary/payroll-run/': typeof AuthenticatedSalaryPayrollRunIndexRoute
  '/_authenticated/salary/region-pool/': typeof AuthenticatedSalaryRegionPoolIndexRoute
  '/_authenticated/salary/rules/': typeof AuthenticatedSalaryRulesIndexRoute
  '/_authenticated/salary/sales-actuals/': typeof AuthenticatedSalarySalesActualsIndexRoute
  '/_authenticated/salary/sales-targets/': typeof AuthenticatedSalarySalesTargetsIndexRoute
  '/_authenticated/salary/setup/': typeof AuthenticatedSalarySetupIndexRoute
  '/_authenticated/salary/year-bonus/': typeof AuthenticatedSalaryYearBonusIndexRoute
  '/_authenticated/sales/ar-adjustments/': typeof AuthenticatedSalesArAdjustmentsIndexRoute
  '/_authenticated/sales/ar-ledgers/': typeof AuthenticatedSalesArLedgersIndexRoute
  '/_authenticated/sales/ar-openings/': typeof AuthenticatedSalesArOpeningsIndexRoute
  '/_authenticated/sales/ar-summary/': typeof AuthenticatedSalesArSummaryIndexRoute
  '/_authenticated/sales/cash-bank-ledger/': typeof AuthenticatedSalesCashBankLedgerIndexRoute
  '/_authenticated/sales/deliveries/': typeof AuthenticatedSalesDeliveriesIndexRoute
  '/_authenticated/sales/exports/': typeof AuthenticatedSalesExportsIndexRoute
  '/_authenticated/sales/goods-descriptions/': typeof AuthenticatedSalesGoodsDescriptionsIndexRoute
  '/_authenticated/sales/inventory-summary/': typeof AuthenticatedSalesInventorySummaryIndexRoute
  '/_authenticated/sales/orders/': typeof AuthenticatedSalesOrdersIndexRoute
  '/_authenticated/sales/receipts/': typeof AuthenticatedSalesReceiptsIndexRoute
  '/_authenticated/sales/returns/': typeof AuthenticatedSalesReturnsIndexRoute
  '/_authenticated/tools/product-merge/': typeof AuthenticatedToolsProductMergeIndexRoute
  '/_authenticated/vip/customer-plan/': typeof AuthenticatedVipCustomerPlanIndexRoute
  '/_authenticated/vip/customer-target/': typeof AuthenticatedVipCustomerTargetIndexRoute
  '/_authenticated/vip/customer/': typeof AuthenticatedVipCustomerIndexRoute
  '/_authenticated/vip/point-rules/': typeof AuthenticatedVipPointRulesIndexRoute
  '/_authenticated/vip/private-rules/': typeof AuthenticatedVipPrivateRulesIndexRoute
  '/_authenticated/vip/product-mapping/': typeof AuthenticatedVipProductMappingIndexRoute
  '/_authenticated/vip/recalc-job/': typeof AuthenticatedVipRecalcJobIndexRoute
  '/_authenticated/vip/tiers/': typeof AuthenticatedVipTiersIndexRoute
  '/_authenticated/production/orders/$id/': typeof AuthenticatedProductionOrdersIdIndexRoute
  '/_authenticated/purchasing/contracts/$id/': typeof AuthenticatedPurchasingContractsIdIndexRoute
  '/_authenticated/salary/payroll-result/$employeeId/': typeof AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute
  '/_authenticated/sales/deliveries/$id/': typeof AuthenticatedSalesDeliveriesIdIndexRoute
  '/_authenticated/sales/exports/$id/': typeof AuthenticatedSalesExportsIdIndexRoute
  '/_authenticated/sales/orders/$id/': typeof AuthenticatedSalesOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/companies/'
    | '/currencies/'
    | '/customers/'
    | '/employees/'
    | '/nations/'
    | '/physical-warehouses/'
    | '/pricing/'
    | '/product-groups/'
    | '/products/'
    | '/provinces/'
    | '/purchasing/'
    | '/regions/'
    | '/transactions/'
    | '/user/'
    | '/warehouses/'
    | '/vip/customer/$id'
    | '/access/permissions/'
    | '/access/roles/'
    | '/access/user-roles/'
    | '/access/users/'
    | '/inventory/inbounds/'
    | '/inventory/ledgers/'
    | '/inventory/lots/'
    | '/inventory/outbounds/'
    | '/inventory/summary/'
    | '/production/boms/'
    | '/production/orders/'
    | '/purchasing/ap-summary/'
    | '/purchasing/contracts/'
    | '/purchasing/ports/'
    | '/purchasing/shipments/'
    | '/purchasing/suppliers/'
    | '/salary/adjustments/'
    | '/salary/audit/'
    | '/salary/import/'
    | '/salary/monthly-incomes/'
    | '/salary/payroll-config/'
    | '/salary/payroll-result/'
    | '/salary/payroll-run/'
    | '/salary/region-pool/'
    | '/salary/rules/'
    | '/salary/sales-actuals/'
    | '/salary/sales-targets/'
    | '/salary/setup/'
    | '/salary/year-bonus/'
    | '/sales/ar-adjustments/'
    | '/sales/ar-ledgers/'
    | '/sales/ar-openings/'
    | '/sales/ar-summary/'
    | '/sales/cash-bank-ledger/'
    | '/sales/deliveries/'
    | '/sales/exports/'
    | '/sales/goods-descriptions/'
    | '/sales/inventory-summary/'
    | '/sales/orders/'
    | '/sales/receipts/'
    | '/sales/returns/'
    | '/tools/product-merge/'
    | '/vip/customer-plan/'
    | '/vip/customer-target/'
    | '/vip/customer/'
    | '/vip/point-rules/'
    | '/vip/private-rules/'
    | '/vip/product-mapping/'
    | '/vip/recalc-job/'
    | '/vip/tiers/'
    | '/production/orders/$id/'
    | '/purchasing/contracts/$id/'
    | '/salary/payroll-result/$employeeId/'
    | '/sales/deliveries/$id/'
    | '/sales/exports/$id/'
    | '/sales/orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/companies'
    | '/currencies'
    | '/customers'
    | '/employees'
    | '/nations'
    | '/physical-warehouses'
    | '/pricing'
    | '/product-groups'
    | '/products'
    | '/provinces'
    | '/purchasing'
    | '/regions'
    | '/transactions'
    | '/user'
    | '/warehouses'
    | '/vip/customer/$id'
    | '/access/permissions'
    | '/access/roles'
    | '/access/user-roles'
    | '/access/users'
    | '/inventory/inbounds'
    | '/inventory/ledgers'
    | '/inventory/lots'
    | '/inventory/outbounds'
    | '/inventory/summary'
    | '/production/boms'
    | '/production/orders'
    | '/purchasing/ap-summary'
    | '/purchasing/contracts'
    | '/purchasing/ports'
    | '/purchasing/shipments'
    | '/purchasing/suppliers'
    | '/salary/adjustments'
    | '/salary/audit'
    | '/salary/import'
    | '/salary/monthly-incomes'
    | '/salary/payroll-config'
    | '/salary/payroll-result'
    | '/salary/payroll-run'
    | '/salary/region-pool'
    | '/salary/rules'
    | '/salary/sales-actuals'
    | '/salary/sales-targets'
    | '/salary/setup'
    | '/salary/year-bonus'
    | '/sales/ar-adjustments'
    | '/sales/ar-ledgers'
    | '/sales/ar-openings'
    | '/sales/ar-summary'
    | '/sales/cash-bank-ledger'
    | '/sales/deliveries'
    | '/sales/exports'
    | '/sales/goods-descriptions'
    | '/sales/inventory-summary'
    | '/sales/orders'
    | '/sales/receipts'
    | '/sales/returns'
    | '/tools/product-merge'
    | '/vip/customer-plan'
    | '/vip/customer-target'
    | '/vip/customer'
    | '/vip/point-rules'
    | '/vip/private-rules'
    | '/vip/product-mapping'
    | '/vip/recalc-job'
    | '/vip/tiers'
    | '/production/orders/$id'
    | '/purchasing/contracts/$id'
    | '/salary/payroll-result/$employeeId'
    | '/sales/deliveries/$id'
    | '/sales/exports/$id'
    | '/sales/orders/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/companies/'
    | '/_authenticated/currencies/'
    | '/_authenticated/customers/'
    | '/_authenticated/employees/'
    | '/_authenticated/nations/'
    | '/_authenticated/physical-warehouses/'
    | '/_authenticated/pricing/'
    | '/_authenticated/product-groups/'
    | '/_authenticated/products/'
    | '/_authenticated/provinces/'
    | '/_authenticated/purchasing/'
    | '/_authenticated/regions/'
    | '/_authenticated/transactions/'
    | '/_authenticated/user/'
    | '/_authenticated/warehouses/'
    | '/_authenticated/vip/customer/$id'
    | '/_authenticated/access/permissions/'
    | '/_authenticated/access/roles/'
    | '/_authenticated/access/user-roles/'
    | '/_authenticated/access/users/'
    | '/_authenticated/inventory/inbounds/'
    | '/_authenticated/inventory/ledgers/'
    | '/_authenticated/inventory/lots/'
    | '/_authenticated/inventory/outbounds/'
    | '/_authenticated/inventory/summary/'
    | '/_authenticated/production/boms/'
    | '/_authenticated/production/orders/'
    | '/_authenticated/purchasing/ap-summary/'
    | '/_authenticated/purchasing/contracts/'
    | '/_authenticated/purchasing/ports/'
    | '/_authenticated/purchasing/shipments/'
    | '/_authenticated/purchasing/suppliers/'
    | '/_authenticated/salary/adjustments/'
    | '/_authenticated/salary/audit/'
    | '/_authenticated/salary/import/'
    | '/_authenticated/salary/monthly-incomes/'
    | '/_authenticated/salary/payroll-config/'
    | '/_authenticated/salary/payroll-result/'
    | '/_authenticated/salary/payroll-run/'
    | '/_authenticated/salary/region-pool/'
    | '/_authenticated/salary/rules/'
    | '/_authenticated/salary/sales-actuals/'
    | '/_authenticated/salary/sales-targets/'
    | '/_authenticated/salary/setup/'
    | '/_authenticated/salary/year-bonus/'
    | '/_authenticated/sales/ar-adjustments/'
    | '/_authenticated/sales/ar-ledgers/'
    | '/_authenticated/sales/ar-openings/'
    | '/_authenticated/sales/ar-summary/'
    | '/_authenticated/sales/cash-bank-ledger/'
    | '/_authenticated/sales/deliveries/'
    | '/_authenticated/sales/exports/'
    | '/_authenticated/sales/goods-descriptions/'
    | '/_authenticated/sales/inventory-summary/'
    | '/_authenticated/sales/orders/'
    | '/_authenticated/sales/receipts/'
    | '/_authenticated/sales/returns/'
    | '/_authenticated/tools/product-merge/'
    | '/_authenticated/vip/customer-plan/'
    | '/_authenticated/vip/customer-target/'
    | '/_authenticated/vip/customer/'
    | '/_authenticated/vip/point-rules/'
    | '/_authenticated/vip/private-rules/'
    | '/_authenticated/vip/product-mapping/'
    | '/_authenticated/vip/recalc-job/'
    | '/_authenticated/vip/tiers/'
    | '/_authenticated/production/orders/$id/'
    | '/_authenticated/purchasing/contracts/$id/'
    | '/_authenticated/salary/payroll-result/$employeeId/'
    | '/_authenticated/sales/deliveries/$id/'
    | '/_authenticated/sales/exports/$id/'
    | '/_authenticated/sales/orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouses/': {
      id: '/_authenticated/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AuthenticatedWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user/': {
      id: '/_authenticated/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthenticatedUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regions/': {
      id: '/_authenticated/regions/'
      path: '/regions'
      fullPath: '/regions/'
      preLoaderRoute: typeof AuthenticatedRegionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/': {
      id: '/_authenticated/purchasing/'
      path: '/purchasing'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof AuthenticatedPurchasingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provinces/': {
      id: '/_authenticated/provinces/'
      path: '/provinces'
      fullPath: '/provinces/'
      preLoaderRoute: typeof AuthenticatedProvincesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-groups/': {
      id: '/_authenticated/product-groups/'
      path: '/product-groups'
      fullPath: '/product-groups/'
      preLoaderRoute: typeof AuthenticatedProductGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing/': {
      id: '/_authenticated/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AuthenticatedPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/physical-warehouses/': {
      id: '/_authenticated/physical-warehouses/'
      path: '/physical-warehouses'
      fullPath: '/physical-warehouses/'
      preLoaderRoute: typeof AuthenticatedPhysicalWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nations/': {
      id: '/_authenticated/nations/'
      path: '/nations'
      fullPath: '/nations/'
      preLoaderRoute: typeof AuthenticatedNationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/currencies/': {
      id: '/_authenticated/currencies/'
      path: '/currencies'
      fullPath: '/currencies/'
      preLoaderRoute: typeof AuthenticatedCurrenciesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/tiers/': {
      id: '/_authenticated/vip/tiers/'
      path: '/vip/tiers'
      fullPath: '/vip/tiers/'
      preLoaderRoute: typeof AuthenticatedVipTiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/recalc-job/': {
      id: '/_authenticated/vip/recalc-job/'
      path: '/vip/recalc-job'
      fullPath: '/vip/recalc-job/'
      preLoaderRoute: typeof AuthenticatedVipRecalcJobIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/product-mapping/': {
      id: '/_authenticated/vip/product-mapping/'
      path: '/vip/product-mapping'
      fullPath: '/vip/product-mapping/'
      preLoaderRoute: typeof AuthenticatedVipProductMappingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/private-rules/': {
      id: '/_authenticated/vip/private-rules/'
      path: '/vip/private-rules'
      fullPath: '/vip/private-rules/'
      preLoaderRoute: typeof AuthenticatedVipPrivateRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/point-rules/': {
      id: '/_authenticated/vip/point-rules/'
      path: '/vip/point-rules'
      fullPath: '/vip/point-rules/'
      preLoaderRoute: typeof AuthenticatedVipPointRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/customer/': {
      id: '/_authenticated/vip/customer/'
      path: '/vip/customer'
      fullPath: '/vip/customer/'
      preLoaderRoute: typeof AuthenticatedVipCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/customer-target/': {
      id: '/_authenticated/vip/customer-target/'
      path: '/vip/customer-target'
      fullPath: '/vip/customer-target/'
      preLoaderRoute: typeof AuthenticatedVipCustomerTargetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/customer-plan/': {
      id: '/_authenticated/vip/customer-plan/'
      path: '/vip/customer-plan'
      fullPath: '/vip/customer-plan/'
      preLoaderRoute: typeof AuthenticatedVipCustomerPlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/product-merge/': {
      id: '/_authenticated/tools/product-merge/'
      path: '/tools/product-merge'
      fullPath: '/tools/product-merge/'
      preLoaderRoute: typeof AuthenticatedToolsProductMergeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/returns/': {
      id: '/_authenticated/sales/returns/'
      path: '/sales/returns'
      fullPath: '/sales/returns/'
      preLoaderRoute: typeof AuthenticatedSalesReturnsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/receipts/': {
      id: '/_authenticated/sales/receipts/'
      path: '/sales/receipts'
      fullPath: '/sales/receipts/'
      preLoaderRoute: typeof AuthenticatedSalesReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/orders/': {
      id: '/_authenticated/sales/orders/'
      path: '/sales/orders'
      fullPath: '/sales/orders/'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/inventory-summary/': {
      id: '/_authenticated/sales/inventory-summary/'
      path: '/sales/inventory-summary'
      fullPath: '/sales/inventory-summary/'
      preLoaderRoute: typeof AuthenticatedSalesInventorySummaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/goods-descriptions/': {
      id: '/_authenticated/sales/goods-descriptions/'
      path: '/sales/goods-descriptions'
      fullPath: '/sales/goods-descriptions/'
      preLoaderRoute: typeof AuthenticatedSalesGoodsDescriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/exports/': {
      id: '/_authenticated/sales/exports/'
      path: '/sales/exports'
      fullPath: '/sales/exports/'
      preLoaderRoute: typeof AuthenticatedSalesExportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/deliveries/': {
      id: '/_authenticated/sales/deliveries/'
      path: '/sales/deliveries'
      fullPath: '/sales/deliveries/'
      preLoaderRoute: typeof AuthenticatedSalesDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/cash-bank-ledger/': {
      id: '/_authenticated/sales/cash-bank-ledger/'
      path: '/sales/cash-bank-ledger'
      fullPath: '/sales/cash-bank-ledger/'
      preLoaderRoute: typeof AuthenticatedSalesCashBankLedgerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/ar-summary/': {
      id: '/_authenticated/sales/ar-summary/'
      path: '/sales/ar-summary'
      fullPath: '/sales/ar-summary/'
      preLoaderRoute: typeof AuthenticatedSalesArSummaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/ar-openings/': {
      id: '/_authenticated/sales/ar-openings/'
      path: '/sales/ar-openings'
      fullPath: '/sales/ar-openings/'
      preLoaderRoute: typeof AuthenticatedSalesArOpeningsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/ar-ledgers/': {
      id: '/_authenticated/sales/ar-ledgers/'
      path: '/sales/ar-ledgers'
      fullPath: '/sales/ar-ledgers/'
      preLoaderRoute: typeof AuthenticatedSalesArLedgersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/ar-adjustments/': {
      id: '/_authenticated/sales/ar-adjustments/'
      path: '/sales/ar-adjustments'
      fullPath: '/sales/ar-adjustments/'
      preLoaderRoute: typeof AuthenticatedSalesArAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/year-bonus/': {
      id: '/_authenticated/salary/year-bonus/'
      path: '/salary/year-bonus'
      fullPath: '/salary/year-bonus/'
      preLoaderRoute: typeof AuthenticatedSalaryYearBonusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/setup/': {
      id: '/_authenticated/salary/setup/'
      path: '/salary/setup'
      fullPath: '/salary/setup/'
      preLoaderRoute: typeof AuthenticatedSalarySetupIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/sales-targets/': {
      id: '/_authenticated/salary/sales-targets/'
      path: '/salary/sales-targets'
      fullPath: '/salary/sales-targets/'
      preLoaderRoute: typeof AuthenticatedSalarySalesTargetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/sales-actuals/': {
      id: '/_authenticated/salary/sales-actuals/'
      path: '/salary/sales-actuals'
      fullPath: '/salary/sales-actuals/'
      preLoaderRoute: typeof AuthenticatedSalarySalesActualsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/rules/': {
      id: '/_authenticated/salary/rules/'
      path: '/salary/rules'
      fullPath: '/salary/rules/'
      preLoaderRoute: typeof AuthenticatedSalaryRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/region-pool/': {
      id: '/_authenticated/salary/region-pool/'
      path: '/salary/region-pool'
      fullPath: '/salary/region-pool/'
      preLoaderRoute: typeof AuthenticatedSalaryRegionPoolIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/payroll-run/': {
      id: '/_authenticated/salary/payroll-run/'
      path: '/salary/payroll-run'
      fullPath: '/salary/payroll-run/'
      preLoaderRoute: typeof AuthenticatedSalaryPayrollRunIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/payroll-result/': {
      id: '/_authenticated/salary/payroll-result/'
      path: '/salary/payroll-result'
      fullPath: '/salary/payroll-result/'
      preLoaderRoute: typeof AuthenticatedSalaryPayrollResultIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/payroll-config/': {
      id: '/_authenticated/salary/payroll-config/'
      path: '/salary/payroll-config'
      fullPath: '/salary/payroll-config/'
      preLoaderRoute: typeof AuthenticatedSalaryPayrollConfigIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/monthly-incomes/': {
      id: '/_authenticated/salary/monthly-incomes/'
      path: '/salary/monthly-incomes'
      fullPath: '/salary/monthly-incomes/'
      preLoaderRoute: typeof AuthenticatedSalaryMonthlyIncomesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/import/': {
      id: '/_authenticated/salary/import/'
      path: '/salary/import'
      fullPath: '/salary/import/'
      preLoaderRoute: typeof AuthenticatedSalaryImportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/audit/': {
      id: '/_authenticated/salary/audit/'
      path: '/salary/audit'
      fullPath: '/salary/audit/'
      preLoaderRoute: typeof AuthenticatedSalaryAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/adjustments/': {
      id: '/_authenticated/salary/adjustments/'
      path: '/salary/adjustments'
      fullPath: '/salary/adjustments/'
      preLoaderRoute: typeof AuthenticatedSalaryAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/suppliers/': {
      id: '/_authenticated/purchasing/suppliers/'
      path: '/purchasing/suppliers'
      fullPath: '/purchasing/suppliers/'
      preLoaderRoute: typeof AuthenticatedPurchasingSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/shipments/': {
      id: '/_authenticated/purchasing/shipments/'
      path: '/purchasing/shipments'
      fullPath: '/purchasing/shipments/'
      preLoaderRoute: typeof AuthenticatedPurchasingShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/ports/': {
      id: '/_authenticated/purchasing/ports/'
      path: '/purchasing/ports'
      fullPath: '/purchasing/ports/'
      preLoaderRoute: typeof AuthenticatedPurchasingPortsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/contracts/': {
      id: '/_authenticated/purchasing/contracts/'
      path: '/purchasing/contracts'
      fullPath: '/purchasing/contracts/'
      preLoaderRoute: typeof AuthenticatedPurchasingContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/ap-summary/': {
      id: '/_authenticated/purchasing/ap-summary/'
      path: '/purchasing/ap-summary'
      fullPath: '/purchasing/ap-summary/'
      preLoaderRoute: typeof AuthenticatedPurchasingApSummaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/orders/': {
      id: '/_authenticated/production/orders/'
      path: '/production/orders'
      fullPath: '/production/orders/'
      preLoaderRoute: typeof AuthenticatedProductionOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/boms/': {
      id: '/_authenticated/production/boms/'
      path: '/production/boms'
      fullPath: '/production/boms/'
      preLoaderRoute: typeof AuthenticatedProductionBomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/summary/': {
      id: '/_authenticated/inventory/summary/'
      path: '/inventory/summary'
      fullPath: '/inventory/summary/'
      preLoaderRoute: typeof AuthenticatedInventorySummaryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/outbounds/': {
      id: '/_authenticated/inventory/outbounds/'
      path: '/inventory/outbounds'
      fullPath: '/inventory/outbounds/'
      preLoaderRoute: typeof AuthenticatedInventoryOutboundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/lots/': {
      id: '/_authenticated/inventory/lots/'
      path: '/inventory/lots'
      fullPath: '/inventory/lots/'
      preLoaderRoute: typeof AuthenticatedInventoryLotsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/ledgers/': {
      id: '/_authenticated/inventory/ledgers/'
      path: '/inventory/ledgers'
      fullPath: '/inventory/ledgers/'
      preLoaderRoute: typeof AuthenticatedInventoryLedgersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/inbounds/': {
      id: '/_authenticated/inventory/inbounds/'
      path: '/inventory/inbounds'
      fullPath: '/inventory/inbounds/'
      preLoaderRoute: typeof AuthenticatedInventoryInboundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/users/': {
      id: '/_authenticated/access/users/'
      path: '/access/users'
      fullPath: '/access/users/'
      preLoaderRoute: typeof AuthenticatedAccessUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/user-roles/': {
      id: '/_authenticated/access/user-roles/'
      path: '/access/user-roles'
      fullPath: '/access/user-roles/'
      preLoaderRoute: typeof AuthenticatedAccessUserRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/roles/': {
      id: '/_authenticated/access/roles/'
      path: '/access/roles'
      fullPath: '/access/roles/'
      preLoaderRoute: typeof AuthenticatedAccessRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/permissions/': {
      id: '/_authenticated/access/permissions/'
      path: '/access/permissions'
      fullPath: '/access/permissions/'
      preLoaderRoute: typeof AuthenticatedAccessPermissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip/customer/$id': {
      id: '/_authenticated/vip/customer/$id'
      path: '/vip/customer/$id'
      fullPath: '/vip/customer/$id'
      preLoaderRoute: typeof AuthenticatedVipCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/orders/$id/': {
      id: '/_authenticated/sales/orders/$id/'
      path: '/sales/orders/$id'
      fullPath: '/sales/orders/$id/'
      preLoaderRoute: typeof AuthenticatedSalesOrdersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/exports/$id/': {
      id: '/_authenticated/sales/exports/$id/'
      path: '/sales/exports/$id'
      fullPath: '/sales/exports/$id/'
      preLoaderRoute: typeof AuthenticatedSalesExportsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/deliveries/$id/': {
      id: '/_authenticated/sales/deliveries/$id/'
      path: '/sales/deliveries/$id'
      fullPath: '/sales/deliveries/$id/'
      preLoaderRoute: typeof AuthenticatedSalesDeliveriesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary/payroll-result/$employeeId/': {
      id: '/_authenticated/salary/payroll-result/$employeeId/'
      path: '/salary/payroll-result/$employeeId'
      fullPath: '/salary/payroll-result/$employeeId/'
      preLoaderRoute: typeof AuthenticatedSalaryPayrollResultEmployeeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchasing/contracts/$id/': {
      id: '/_authenticated/purchasing/contracts/$id/'
      path: '/purchasing/contracts/$id'
      fullPath: '/purchasing/contracts/$id/'
      preLoaderRoute: typeof AuthenticatedPurchasingContractsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/orders/$id/': {
      id: '/_authenticated/production/orders/$id/'
      path: '/production/orders/$id'
      fullPath: '/production/orders/$id/'
      preLoaderRoute: typeof AuthenticatedProductionOrdersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedCurrenciesIndexRoute: typeof AuthenticatedCurrenciesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedNationsIndexRoute: typeof AuthenticatedNationsIndexRoute
  AuthenticatedPhysicalWarehousesIndexRoute: typeof AuthenticatedPhysicalWarehousesIndexRoute
  AuthenticatedPricingIndexRoute: typeof AuthenticatedPricingIndexRoute
  AuthenticatedProductGroupsIndexRoute: typeof AuthenticatedProductGroupsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProvincesIndexRoute: typeof AuthenticatedProvincesIndexRoute
  AuthenticatedPurchasingIndexRoute: typeof AuthenticatedPurchasingIndexRoute
  AuthenticatedRegionsIndexRoute: typeof AuthenticatedRegionsIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedUserIndexRoute: typeof AuthenticatedUserIndexRoute
  AuthenticatedWarehousesIndexRoute: typeof AuthenticatedWarehousesIndexRoute
  AuthenticatedVipCustomerIdRoute: typeof AuthenticatedVipCustomerIdRoute
  AuthenticatedAccessPermissionsIndexRoute: typeof AuthenticatedAccessPermissionsIndexRoute
  AuthenticatedAccessRolesIndexRoute: typeof AuthenticatedAccessRolesIndexRoute
  AuthenticatedAccessUserRolesIndexRoute: typeof AuthenticatedAccessUserRolesIndexRoute
  AuthenticatedAccessUsersIndexRoute: typeof AuthenticatedAccessUsersIndexRoute
  AuthenticatedInventoryInboundsIndexRoute: typeof AuthenticatedInventoryInboundsIndexRoute
  AuthenticatedInventoryLedgersIndexRoute: typeof AuthenticatedInventoryLedgersIndexRoute
  AuthenticatedInventoryLotsIndexRoute: typeof AuthenticatedInventoryLotsIndexRoute
  AuthenticatedInventoryOutboundsIndexRoute: typeof AuthenticatedInventoryOutboundsIndexRoute
  AuthenticatedInventorySummaryIndexRoute: typeof AuthenticatedInventorySummaryIndexRoute
  AuthenticatedProductionBomsIndexRoute: typeof AuthenticatedProductionBomsIndexRoute
  AuthenticatedProductionOrdersIndexRoute: typeof AuthenticatedProductionOrdersIndexRoute
  AuthenticatedPurchasingApSummaryIndexRoute: typeof AuthenticatedPurchasingApSummaryIndexRoute
  AuthenticatedPurchasingContractsIndexRoute: typeof AuthenticatedPurchasingContractsIndexRoute
  AuthenticatedPurchasingPortsIndexRoute: typeof AuthenticatedPurchasingPortsIndexRoute
  AuthenticatedPurchasingShipmentsIndexRoute: typeof AuthenticatedPurchasingShipmentsIndexRoute
  AuthenticatedPurchasingSuppliersIndexRoute: typeof AuthenticatedPurchasingSuppliersIndexRoute
  AuthenticatedSalaryAdjustmentsIndexRoute: typeof AuthenticatedSalaryAdjustmentsIndexRoute
  AuthenticatedSalaryAuditIndexRoute: typeof AuthenticatedSalaryAuditIndexRoute
  AuthenticatedSalaryImportIndexRoute: typeof AuthenticatedSalaryImportIndexRoute
  AuthenticatedSalaryMonthlyIncomesIndexRoute: typeof AuthenticatedSalaryMonthlyIncomesIndexRoute
  AuthenticatedSalaryPayrollConfigIndexRoute: typeof AuthenticatedSalaryPayrollConfigIndexRoute
  AuthenticatedSalaryPayrollResultIndexRoute: typeof AuthenticatedSalaryPayrollResultIndexRoute
  AuthenticatedSalaryPayrollRunIndexRoute: typeof AuthenticatedSalaryPayrollRunIndexRoute
  AuthenticatedSalaryRegionPoolIndexRoute: typeof AuthenticatedSalaryRegionPoolIndexRoute
  AuthenticatedSalaryRulesIndexRoute: typeof AuthenticatedSalaryRulesIndexRoute
  AuthenticatedSalarySalesActualsIndexRoute: typeof AuthenticatedSalarySalesActualsIndexRoute
  AuthenticatedSalarySalesTargetsIndexRoute: typeof AuthenticatedSalarySalesTargetsIndexRoute
  AuthenticatedSalarySetupIndexRoute: typeof AuthenticatedSalarySetupIndexRoute
  AuthenticatedSalaryYearBonusIndexRoute: typeof AuthenticatedSalaryYearBonusIndexRoute
  AuthenticatedSalesArAdjustmentsIndexRoute: typeof AuthenticatedSalesArAdjustmentsIndexRoute
  AuthenticatedSalesArLedgersIndexRoute: typeof AuthenticatedSalesArLedgersIndexRoute
  AuthenticatedSalesArOpeningsIndexRoute: typeof AuthenticatedSalesArOpeningsIndexRoute
  AuthenticatedSalesArSummaryIndexRoute: typeof AuthenticatedSalesArSummaryIndexRoute
  AuthenticatedSalesCashBankLedgerIndexRoute: typeof AuthenticatedSalesCashBankLedgerIndexRoute
  AuthenticatedSalesDeliveriesIndexRoute: typeof AuthenticatedSalesDeliveriesIndexRoute
  AuthenticatedSalesExportsIndexRoute: typeof AuthenticatedSalesExportsIndexRoute
  AuthenticatedSalesGoodsDescriptionsIndexRoute: typeof AuthenticatedSalesGoodsDescriptionsIndexRoute
  AuthenticatedSalesInventorySummaryIndexRoute: typeof AuthenticatedSalesInventorySummaryIndexRoute
  AuthenticatedSalesOrdersIndexRoute: typeof AuthenticatedSalesOrdersIndexRoute
  AuthenticatedSalesReceiptsIndexRoute: typeof AuthenticatedSalesReceiptsIndexRoute
  AuthenticatedSalesReturnsIndexRoute: typeof AuthenticatedSalesReturnsIndexRoute
  AuthenticatedToolsProductMergeIndexRoute: typeof AuthenticatedToolsProductMergeIndexRoute
  AuthenticatedVipCustomerPlanIndexRoute: typeof AuthenticatedVipCustomerPlanIndexRoute
  AuthenticatedVipCustomerTargetIndexRoute: typeof AuthenticatedVipCustomerTargetIndexRoute
  AuthenticatedVipCustomerIndexRoute: typeof AuthenticatedVipCustomerIndexRoute
  AuthenticatedVipPointRulesIndexRoute: typeof AuthenticatedVipPointRulesIndexRoute
  AuthenticatedVipPrivateRulesIndexRoute: typeof AuthenticatedVipPrivateRulesIndexRoute
  AuthenticatedVipProductMappingIndexRoute: typeof AuthenticatedVipProductMappingIndexRoute
  AuthenticatedVipRecalcJobIndexRoute: typeof AuthenticatedVipRecalcJobIndexRoute
  AuthenticatedVipTiersIndexRoute: typeof AuthenticatedVipTiersIndexRoute
  AuthenticatedProductionOrdersIdIndexRoute: typeof AuthenticatedProductionOrdersIdIndexRoute
  AuthenticatedPurchasingContractsIdIndexRoute: typeof AuthenticatedPurchasingContractsIdIndexRoute
  AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute: typeof AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute
  AuthenticatedSalesDeliveriesIdIndexRoute: typeof AuthenticatedSalesDeliveriesIdIndexRoute
  AuthenticatedSalesExportsIdIndexRoute: typeof AuthenticatedSalesExportsIdIndexRoute
  AuthenticatedSalesOrdersIdIndexRoute: typeof AuthenticatedSalesOrdersIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedCurrenciesIndexRoute: AuthenticatedCurrenciesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedNationsIndexRoute: AuthenticatedNationsIndexRoute,
  AuthenticatedPhysicalWarehousesIndexRoute:
    AuthenticatedPhysicalWarehousesIndexRoute,
  AuthenticatedPricingIndexRoute: AuthenticatedPricingIndexRoute,
  AuthenticatedProductGroupsIndexRoute: AuthenticatedProductGroupsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProvincesIndexRoute: AuthenticatedProvincesIndexRoute,
  AuthenticatedPurchasingIndexRoute: AuthenticatedPurchasingIndexRoute,
  AuthenticatedRegionsIndexRoute: AuthenticatedRegionsIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedUserIndexRoute: AuthenticatedUserIndexRoute,
  AuthenticatedWarehousesIndexRoute: AuthenticatedWarehousesIndexRoute,
  AuthenticatedVipCustomerIdRoute: AuthenticatedVipCustomerIdRoute,
  AuthenticatedAccessPermissionsIndexRoute:
    AuthenticatedAccessPermissionsIndexRoute,
  AuthenticatedAccessRolesIndexRoute: AuthenticatedAccessRolesIndexRoute,
  AuthenticatedAccessUserRolesIndexRoute:
    AuthenticatedAccessUserRolesIndexRoute,
  AuthenticatedAccessUsersIndexRoute: AuthenticatedAccessUsersIndexRoute,
  AuthenticatedInventoryInboundsIndexRoute:
    AuthenticatedInventoryInboundsIndexRoute,
  AuthenticatedInventoryLedgersIndexRoute:
    AuthenticatedInventoryLedgersIndexRoute,
  AuthenticatedInventoryLotsIndexRoute: AuthenticatedInventoryLotsIndexRoute,
  AuthenticatedInventoryOutboundsIndexRoute:
    AuthenticatedInventoryOutboundsIndexRoute,
  AuthenticatedInventorySummaryIndexRoute:
    AuthenticatedInventorySummaryIndexRoute,
  AuthenticatedProductionBomsIndexRoute: AuthenticatedProductionBomsIndexRoute,
  AuthenticatedProductionOrdersIndexRoute:
    AuthenticatedProductionOrdersIndexRoute,
  AuthenticatedPurchasingApSummaryIndexRoute:
    AuthenticatedPurchasingApSummaryIndexRoute,
  AuthenticatedPurchasingContractsIndexRoute:
    AuthenticatedPurchasingContractsIndexRoute,
  AuthenticatedPurchasingPortsIndexRoute:
    AuthenticatedPurchasingPortsIndexRoute,
  AuthenticatedPurchasingShipmentsIndexRoute:
    AuthenticatedPurchasingShipmentsIndexRoute,
  AuthenticatedPurchasingSuppliersIndexRoute:
    AuthenticatedPurchasingSuppliersIndexRoute,
  AuthenticatedSalaryAdjustmentsIndexRoute:
    AuthenticatedSalaryAdjustmentsIndexRoute,
  AuthenticatedSalaryAuditIndexRoute: AuthenticatedSalaryAuditIndexRoute,
  AuthenticatedSalaryImportIndexRoute: AuthenticatedSalaryImportIndexRoute,
  AuthenticatedSalaryMonthlyIncomesIndexRoute:
    AuthenticatedSalaryMonthlyIncomesIndexRoute,
  AuthenticatedSalaryPayrollConfigIndexRoute:
    AuthenticatedSalaryPayrollConfigIndexRoute,
  AuthenticatedSalaryPayrollResultIndexRoute:
    AuthenticatedSalaryPayrollResultIndexRoute,
  AuthenticatedSalaryPayrollRunIndexRoute:
    AuthenticatedSalaryPayrollRunIndexRoute,
  AuthenticatedSalaryRegionPoolIndexRoute:
    AuthenticatedSalaryRegionPoolIndexRoute,
  AuthenticatedSalaryRulesIndexRoute: AuthenticatedSalaryRulesIndexRoute,
  AuthenticatedSalarySalesActualsIndexRoute:
    AuthenticatedSalarySalesActualsIndexRoute,
  AuthenticatedSalarySalesTargetsIndexRoute:
    AuthenticatedSalarySalesTargetsIndexRoute,
  AuthenticatedSalarySetupIndexRoute: AuthenticatedSalarySetupIndexRoute,
  AuthenticatedSalaryYearBonusIndexRoute:
    AuthenticatedSalaryYearBonusIndexRoute,
  AuthenticatedSalesArAdjustmentsIndexRoute:
    AuthenticatedSalesArAdjustmentsIndexRoute,
  AuthenticatedSalesArLedgersIndexRoute: AuthenticatedSalesArLedgersIndexRoute,
  AuthenticatedSalesArOpeningsIndexRoute:
    AuthenticatedSalesArOpeningsIndexRoute,
  AuthenticatedSalesArSummaryIndexRoute: AuthenticatedSalesArSummaryIndexRoute,
  AuthenticatedSalesCashBankLedgerIndexRoute:
    AuthenticatedSalesCashBankLedgerIndexRoute,
  AuthenticatedSalesDeliveriesIndexRoute:
    AuthenticatedSalesDeliveriesIndexRoute,
  AuthenticatedSalesExportsIndexRoute: AuthenticatedSalesExportsIndexRoute,
  AuthenticatedSalesGoodsDescriptionsIndexRoute:
    AuthenticatedSalesGoodsDescriptionsIndexRoute,
  AuthenticatedSalesInventorySummaryIndexRoute:
    AuthenticatedSalesInventorySummaryIndexRoute,
  AuthenticatedSalesOrdersIndexRoute: AuthenticatedSalesOrdersIndexRoute,
  AuthenticatedSalesReceiptsIndexRoute: AuthenticatedSalesReceiptsIndexRoute,
  AuthenticatedSalesReturnsIndexRoute: AuthenticatedSalesReturnsIndexRoute,
  AuthenticatedToolsProductMergeIndexRoute:
    AuthenticatedToolsProductMergeIndexRoute,
  AuthenticatedVipCustomerPlanIndexRoute:
    AuthenticatedVipCustomerPlanIndexRoute,
  AuthenticatedVipCustomerTargetIndexRoute:
    AuthenticatedVipCustomerTargetIndexRoute,
  AuthenticatedVipCustomerIndexRoute: AuthenticatedVipCustomerIndexRoute,
  AuthenticatedVipPointRulesIndexRoute: AuthenticatedVipPointRulesIndexRoute,
  AuthenticatedVipPrivateRulesIndexRoute:
    AuthenticatedVipPrivateRulesIndexRoute,
  AuthenticatedVipProductMappingIndexRoute:
    AuthenticatedVipProductMappingIndexRoute,
  AuthenticatedVipRecalcJobIndexRoute: AuthenticatedVipRecalcJobIndexRoute,
  AuthenticatedVipTiersIndexRoute: AuthenticatedVipTiersIndexRoute,
  AuthenticatedProductionOrdersIdIndexRoute:
    AuthenticatedProductionOrdersIdIndexRoute,
  AuthenticatedPurchasingContractsIdIndexRoute:
    AuthenticatedPurchasingContractsIdIndexRoute,
  AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute:
    AuthenticatedSalaryPayrollResultEmployeeIdIndexRoute,
  AuthenticatedSalesDeliveriesIdIndexRoute:
    AuthenticatedSalesDeliveriesIdIndexRoute,
  AuthenticatedSalesExportsIdIndexRoute: AuthenticatedSalesExportsIdIndexRoute,
  AuthenticatedSalesOrdersIdIndexRoute: AuthenticatedSalesOrdersIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
